// widgets/add_customer_modal.dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../models/customer.dart';
import '../models/invoice.dart';
import '../services/supabase_service.dart';
import 'package:provider/provider.dart';
import '../state/app_state.dart';

class AddCustomerModal extends StatefulWidget {
  const AddCustomerModal({super.key});

  @override
  State<AddCustomerModal> createState() => _AddCustomerModalState();
}

class _AddCustomerModalState extends State<AddCustomerModal> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _amountController = TextEditingController();
  final _descriptionController = TextEditingController();
  late final TextEditingController _startDateController;

  int _repeat = 1;
  DateTime _startDate = DateTime.now();
  bool _isLoading = false;
  String? _selectedClass;

  // List of available classes
  final List<String> _availableClasses = [
    'LKG',
    'UKG',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
  ];

  @override
  void initState() {
    super.initState();
    _startDateController = TextEditingController(
      text: '${_startDate.day}/${_startDate.month}/${_startDate.year}',
    );
  }

  @override
  void dispose() {
    _nameController.dispose();
    _amountController.dispose();
    _descriptionController.dispose();
    _startDateController.dispose();
    super.dispose();
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _startDate,
      firstDate: DateTime.now().subtract(const Duration(days: 365)),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );

    if (picked != null) {
      setState(() {
        _startDate = picked;
        _startDateController.text =
            '${_startDate.day}/${_startDate.month}/${_startDate.year}';
      });
    }
  }

  DateTime get _endDate {
    return DateTime(
      _startDate.year,
      _startDate.month + _repeat,
      _startDate.day,
    );
  }

  Future<void> _saveCustomer() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() {
      _isLoading = true;
    });

    try {
      // Create customer
      final customer = Customer(
        id: '', // Will be generated by Supabase
        userId: SupabaseService().currentUser!.id,
        name: _nameController.text.trim(),
        amount: _amountController.text.isNotEmpty
            ? double.parse(_amountController.text)
            : null,
        description: _descriptionController.text.trim().isEmpty
            ? null
            : _descriptionController.text.trim(),
        studentClass: _selectedClass,
        repeat: _repeat,
        startDate: _startDate,
        endDate: _endDate,
        createdAt: DateTime.now(),
      );
      // Debug prints to terminal
      print(
        '[AddCustomerModal] Creating customer with: '
                '{userId: ' +
            customer.userId +
            ', name: ' +
            customer.name +
            ', amount: ' +
            (customer.amount?.toString() ?? 'null') +
            ', description: ' +
            (customer.description ?? 'null') +
            ', repeat: ' +
            customer.repeat.toString() +
            ', start_date: ' +
            customer.startDate.toIso8601String() +
            ', end_date: ' +
            customer.endDate.toIso8601String() +
            '}',
      );

      final savedCustomer = await SupabaseService().createCustomer(customer);

      // Generate invoices if amount is provided
      if (customer.amount != null && customer.amount! > 0) {
        await _generateInvoices(savedCustomer);
      }

      if (mounted) {
        final appState = Provider.of<AppState>(context, listen: false);
        appState.onCustomerAdded(savedCustomer);
        await appState.recomputeTotals();
        Navigator.of(context).pop(savedCustomer);
      }
    } catch (e, st) {
      // Also log to terminal for debugging
      print('[AddCustomerModal] Error creating customer: ' + e.toString());
      print(st);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error creating customer: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  Future<void> _generateInvoices(Customer customer) async {
    final amount = customer.amount!;
    final dueDates = <DateTime>[];

    // Generate due dates
    for (int i = 0; i < customer.repeat; i++) {
      dueDates.add(
        DateTime(
          customer.startDate.year,
          customer.startDate.month + i,
          customer.startDate.day,
        ),
      );
    }

    // Create invoices
    for (int i = 0; i < dueDates.length; i++) {
      final invoice = Invoice(
        id: '', // Will be generated by Supabase
        customerId: customer.id,
        dueDate: dueDates[i],
        amount: amount,
        status: InvoiceStatus.pending,
        paidAmount: 0,
        description: customer.description,
        createdAt: DateTime.now(),
      );

      await SupabaseService().createInvoice(invoice);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: Container(
        constraints: BoxConstraints(
          maxWidth: MediaQuery.of(context).size.width * 0.95,
          maxHeight: MediaQuery.of(context).size.height * 0.85,
        ),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Header - Fixed at top
                Row(
                  children: [
                    Icon(
                      Icons.person_add,
                      color: Theme.of(context).primaryColor,
                      size: 22,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'Add New Customer',
                        style: Theme.of(context).textTheme.titleLarge?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.close, size: 20),
                      onPressed: () => Navigator.of(context).pop(),
                      padding: EdgeInsets.zero,
                      constraints: const BoxConstraints(
                        minWidth: 32,
                        minHeight: 32,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 20),

                // Scrollable content
                Expanded(
                  child: SingleChildScrollView(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Row(
                        //   children: [
                        //     Icon(
                        //       Icons.person_add,
                        //       color: Theme.of(context).primaryColor,
                        //       size: 24,
                        //     ),
                        //     //  const SizedBox(width: 8),
                        //     // Text(
                        //     //   'Add New Customer',
                        //     //   style: Theme.of(context).textTheme.headlineSmall
                        //     //       ?.copyWith(fontWeight: FontWeight.bold),
                        //     // ),
                        //   ],
                        // ),
                        const SizedBox(height: 24),

                        // Name Field
                        TextFormField(
                          controller: _nameController,
                          decoration: const InputDecoration(
                            labelText: 'Customer Name *',
                            prefixIcon: Icon(Icons.person),
                            border: OutlineInputBorder(),
                          ),
                          validator: (value) {
                            if (value == null || value.trim().isEmpty) {
                              return 'Please enter customer name';
                            }
                            return null;
                          },
                        ),
                        const SizedBox(height: 12),

                        // Amount Field
                        TextFormField(
                          controller: _amountController,
                          keyboardType: const TextInputType.numberWithOptions(
                            decimal: true,
                          ),
                          inputFormatters: [
                            FilteringTextInputFormatter.allow(
                              RegExp(r'^\d*\.?\d*'),
                            ),
                          ],
                          decoration: InputDecoration(
                            labelText: 'Amount (Optional)',
                            prefixIcon: Container(
                              margin: const EdgeInsets.all(12),
                              child: const Text(
                                '₹',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w600,
                                  color: Color(0xFF6366F1),
                                ),
                              ),
                            ),
                            border: OutlineInputBorder(),
                            hintText: 'e.g., 1000',
                          ),
                        ),
                        const SizedBox(height: 12),

                        // Class Field
                        DropdownButtonFormField<String>(
                          value: _selectedClass,
                          decoration: const InputDecoration(
                            labelText: 'Class (Optional)',
                            prefixIcon: Icon(Icons.school),
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 16,
                            ),
                          ),
                          hint: const Text('Select class'),
                          items: _availableClasses.map((String classValue) {
                            return DropdownMenuItem<String>(
                              value: classValue,
                              child: Text(classValue),
                            );
                          }).toList(),
                          onChanged: (String? newValue) {
                            setState(() {
                              _selectedClass = newValue;
                            });
                          },
                        ),
                        const SizedBox(height: 12),

                        // Description Field
                        TextFormField(
                          controller: _descriptionController,
                          maxLines: 3,
                          decoration: const InputDecoration(
                            labelText: 'Description (Optional)',
                            prefixIcon: Icon(Icons.description),
                            border: OutlineInputBorder(),
                            hintText: 'Enter any additional details...',
                          ),
                        ),
                        const SizedBox(height: 12),

                        // Repeat Field
                        DropdownButtonFormField<int>(
                          value: _repeat,
                          decoration: const InputDecoration(
                            labelText: 'Repeat',
                            prefixIcon: Icon(Icons.repeat),
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 16,
                            ),
                          ),
                          items: List.generate(12, (index) => index + 1)
                              .map(
                                (value) => DropdownMenuItem(
                                  value: value,
                                  child: Text(
                                    '$value month${value > 1 ? 's' : ''}',
                                  ),
                                ),
                              )
                              .toList(),
                          onChanged: (value) {
                            setState(() {
                              _repeat = value!;
                            });
                          },
                        ),
                        const SizedBox(height: 12),

                        // Start Date Field
                        TextFormField(
                          controller: _startDateController,
                          readOnly: true,
                          onTap: _selectDate,
                          decoration: const InputDecoration(
                            labelText: 'Start Date',
                            prefixIcon: Icon(Icons.calendar_today),
                            border: OutlineInputBorder(),
                          ),
                        ),
                        const SizedBox(height: 12),

                        // End Date Display
                        Container(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 12,
                            vertical: 8,
                          ),
                          decoration: BoxDecoration(
                            color: Colors.grey[100],
                            borderRadius: BorderRadius.circular(8),
                            border: Border.all(color: Colors.grey[300]!),
                          ),
                          child: Row(
                            children: [
                              const Icon(
                                Icons.event,
                                size: 18,
                                color: Colors.grey,
                              ),
                              const SizedBox(width: 8),
                              Text(
                                'End Date: ${_endDate.day}/${_endDate.month}/${_endDate.year}',
                                style: Theme.of(context).textTheme.bodyMedium
                                    ?.copyWith(
                                      color: Colors.grey[700],
                                      fontWeight: FontWeight.w500,
                                    ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),

                // Action Buttons - Fixed at bottom
                const SizedBox(height: 20),
                Row(
                  children: [
                    Expanded(
                      child: OutlinedButton(
                        onPressed: _isLoading
                            ? null
                            : () => Navigator.of(context).pop(),
                        style: OutlinedButton.styleFrom(
                          padding: const EdgeInsets.symmetric(vertical: 12),
                        ),
                        child: const Text('Cancel'),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: ElevatedButton(
                        onPressed: _isLoading ? null : _saveCustomer,
                        style: ElevatedButton.styleFrom(
                          padding: const EdgeInsets.symmetric(vertical: 12),
                        ),
                        child: _isLoading
                            ? const SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  color: Colors.white,
                                ),
                              )
                            : const Text('Save Customer'),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
